#!/bin/bash

. ./.env
response_subscription=$(curl -s "https://api.openai.com/dashboard/billing/subscription" \
                        -H "Authorization: Bearer $OPENAI_API_KEY")
errorkey_subscription=$(echo "$response_subscription" | jq '.error')
if [ "$errorkey_subscription" = "null" ]; then
    echo "No error occurs with /dashborad/billing/subsription"
else
    echo "Error occurs with /dashborad/billing/subsription"
    echo "Message: " $response_subscription
fi
response_usage=$(curl -s "https://api.openai.com/dashboard/billing/usage?start_date=2023-04-01&end_date=2023-04-02" \
                 -H "Authorization: Bearer $OPENAI_API_KEY")
errorkey_usage=$(echo "$response_usage" | jq '.error')
if [ "$errorkey_usage" = "null" ]; then
    echo "No error occurs with /dashborad/billing/usage"
else
    echo "Error occurs with /dashborad/billing/usage"
    echo "Message: " $response_usage
fi